-- 去玩咯 / 旅行清单：Supabase 标准建表方案
-- 用途：保证 travel/index.html 的 ☁️ 云上传 / ☁️ 云下载 稳定可用

create table if not exists public.travel_items (
  id bigint generated by default as identity primary key,
  household_id text not null,
  category text not null,
  item_name text not null,
  checked boolean not null default false,
  updated_at timestamptz not null default now()
);

create unique index if not exists travel_items_household_category_item_name_uidx
  on public.travel_items (household_id, category, item_name);

create index if not exists travel_items_household_id_idx
  on public.travel_items (household_id);

alter table public.travel_items enable row level security;

-- 公开匿名 key 场景下，允许同一前端直接读写。
-- 当前项目是家庭自用工具站，所以先走简单策略。
drop policy if exists "travel_items_select_all" on public.travel_items;
create policy "travel_items_select_all"
  on public.travel_items
  for select
  to anon, authenticated
  using (true);

drop policy if exists "travel_items_insert_all" on public.travel_items;
create policy "travel_items_insert_all"
  on public.travel_items
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "travel_items_update_all" on public.travel_items;
create policy "travel_items_update_all"
  on public.travel_items
  for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "travel_items_delete_all" on public.travel_items;
create policy "travel_items_delete_all"
  on public.travel_items
  for delete
  to anon, authenticated
  using (true);
