export class Soundtrack {
  constructor(muted=false){this.muted=muted;this.ctx=null;this.voices=new Set();this.lastTick=0;this.lastImpact={wood:0,metal:0};this.roll=null;}
  unlock(){if(!this.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;try{this.ctx=new C();this.master=this.ctx.createGain();this.master.gain.value=this.muted?0:.48;const compressor=this.ctx.createDynamicsCompressor();compressor.threshold.value=-16;compressor.ratio.value=5;this.master.connect(compressor);compressor.connect(this.ctx.destination)}catch{return}}if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});}
  setMuted(value){this.muted=value;if(this.ctx)this.master.gain.setTargetAtTime(value?0:.48,this.ctx.currentTime,.025)}
  tone(freq,start,duration,type='sine',volume=.15,endFreq,pan=0){if(!this.ctx||this.muted)return;const t=this.ctx.currentTime+start,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(endFreq)o.frequency.exponentialRampToValueAtTime(endFreq,t+duration);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0002,volume),t+.009);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);const stereo=this.ctx.createStereoPanner();stereo.pan.value=pan;g.connect(stereo);stereo.connect(this.master);o.start(t);o.stop(t+duration+.03);this.voices.add(o);o.onended=()=>{this.voices.delete(o);o.disconnect();g.disconnect();stereo.disconnect()};}
  start(){this.tone(80,0,.55,'sine',.23,320);this.tone(220,.06,.42,'triangle',.07,880);this.tone(660,.3,.3,'sine',.08);}
  tick(energy){if(!this.ctx||this.muted)return;const now=this.ctx.currentTime;if(now-this.lastTick<.037)return;this.lastTick=now;this.tone(900+energy*1000,0,.035,'triangle',.05);this.tone(160,0,.045,'sine',.1)}
  reveal(gold){const notes=gold?[523.25,659.25,783.99,1046.5,1318.5,1567.98]:[523.25,659.25,783.99,1046.5];notes.forEach((n,i)=>{this.tone(n,i*.095,.8,'sine',.11);this.tone(n*2,i*.095,.38,'sine',.026)});const delay=gold?.55:.34;[261.63,329.63,392,523.25].forEach(n=>this.tone(n,delay,gold?1.7:1.1,'triangle',.033));if(gold){this.tone(65.4,0,.8,'sine',.22);[2093,2637,3136].forEach((n,i)=>this.tone(n,.85+i*.13,.7,'sine',.04))}}
  confirm(){this.tone(659.25,0,.2,'sine',.07);this.tone(987.77,.1,.35,'sine',.06)}
  noise(duration,volume,frequency,pan=0){
    if(!this.ctx||this.muted)return;const ctx=this.ctx,n=ctx.createBufferSource(),g=ctx.createGain(),f=ctx.createBiquadFilter(),p=ctx.createStereoPanner();const b=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*duration),ctx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1);n.buffer=b;f.type='bandpass';f.frequency.value=frequency;f.Q.value=1.1;p.pan.value=pan;g.gain.setValueAtTime(volume,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+duration);n.connect(f);f.connect(g);g.connect(p);p.connect(this.master);n.start();this.voices.add(n);n.onended=()=>{this.voices.delete(n);[n,f,g,p].forEach(x=>x.disconnect())};
  }
  impact({material,speed,position}){
    if(!this.ctx||this.muted)return;const now=this.ctx.currentTime;if(now-this.lastImpact[material]<.042)return;this.lastImpact[material]=now;const v=Math.min(.18,.026+Math.sqrt(speed)*.035),pan=Math.max(-.8,Math.min(.8,position.x/4));
    if(material==='metal'){const detune=.97+Math.random()*.06;[[2150,.19,1],[3710,.12,.48],[5890,.075,.22]].forEach(([f,d,g])=>this.tone(f*detune,0,d,'sine',v*g,undefined,pan));this.noise(.022,v*.45,4300,pan)}
    else{this.tone(175+Math.random()*45,0,.095,'sine',v*.85,105,pan);this.tone(380,0,.045,'triangle',v*.22,undefined,pan);this.noise(.055,v*.7,780,pan)}
  }
  startRolling(){
    if(!this.ctx)return;const c=this.ctx,b=c.createBuffer(1,c.sampleRate,c.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1;const source=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain(),pan=c.createStereoPanner();source.buffer=b;source.loop=true;filter.type='lowpass';filter.frequency.value=900;gain.gain.value=0;source.connect(filter);filter.connect(gain);gain.connect(pan);pan.connect(this.master);source.start();this.voices.add(source);this.roll={source,filter,gain,pan};source.onended=()=>{this.voices.delete(source);[source,filter,gain,pan].forEach(x=>x.disconnect())};
  }
  updateRolling(speed,x,y){if(!this.roll||!this.ctx)return;const t=this.ctx.currentTime;this.roll.gain.gain.setTargetAtTime(Math.min(.04,speed*.005)*(y>.1?1:.35),t,.07);this.roll.filter.frequency.setTargetAtTime(280+speed*170,t,.08);this.roll.pan.pan.setTargetAtTime(Math.max(-.8,Math.min(.8,x/4)),t,.04)}
  stopRolling(){if(this.roll){try{this.roll.source.stop()}catch{}this.roll=null}}
  stop(){this.roll=null;this.voices.forEach(o=>{try{o.stop()}catch{}});this.voices.clear()}
}
