import {dimensions,blankSubject,read,write,validate,parseBackup,merge} from './store.js';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let state,draft,baseRevision,busy=false;
function radar(s){const point=(i,v,r=92)=>[160+Math.sin(i*Math.PI/4)*r*v/5,140-Math.cos(i*Math.PI/4)*r*v/5];const pts=v=>dimensions.map((_,i)=>point(i,v).join(',')).join(' ');let svg='<svg class="radar" viewBox="0 0 320 290" role="img" aria-label="八维雷达图，空白维度未评分">';for(let v=1;v<=5;v++)svg+=`<polygon points="${pts(v)}" fill="none" stroke="#bdd1ca"/>`;dimensions.forEach((d,i)=>{const [x,y]=point(i,5,123);svg+=`<text x="${x}" y="${y}" text-anchor="middle" font-size="10" fill="#234e50">${i===1?'交通':d}</text>`;const p=point(i,5);svg+=`<path d="M160 140 L${p.join(' ')}" stroke="#bdd1ca"/>`});s.ratings.forEach((v,i)=>{if(v===null)return;const p=point(i,v),next=s.ratings[(i+1)%8];if(next!==null)svg+=`<path d="M${p.join(' ')} L${point((i+1)%8,next).join(' ')}" stroke="#2c7776" stroke-width="3"/>`;svg+=`<circle cx="${p[0]}" cy="${p[1]}" r="4" fill="#2c7776"/>`});return svg+'</svg>'}
function render(){ $('#records').innerHTML=state.records.length?state.records.map(r=>`<article class="card"><h2>${esc(r.island)}</h2><p>${esc(r.start||'开始日期待补')} — ${esc(r.end||'结束日期待补')}</p>${r.conflictOf?'<p>⚠️ 导入冲突副本：请核对后编辑或删除。</p>':''}${r.subjects.map(s=>`<h3>${s.kind==='island'?'海岛整体':esc(s.name)}</h3>${radar(s)}<p class="meta">${dimensions.map((d,i)=>`${d} ${s.ratings[i]??'未评分'}`).join(' · ')}</p><p>${esc(s.note)}</p>`).join('')}<p>${esc(r.note)}</p><p class="meta">本机最后保存 ${esc(new Date(r.updatedAt).toLocaleString())}${r.importedAt?' · 导入 '+esc(new Date(r.importedAt).toLocaleString()):''}</p><button data-edit="${esc(r.id)}">编辑这次旅行</button><button data-delete="${esc(r.id)}">删除</button></article>`).join(''):'<p class="empty">🐚 还没有手记<br>从一次真实的旅行开始吧。</p>';$('#islands').innerHTML=[...new Set(state.records.map(r=>r.island))].map(n=>`<option value="${esc(n)}">`).join('');$('#status').textContent=`${state.records.length} 次旅行已存本机。云存档未接入。`}
function subjects(){ $('#subjects').innerHTML=draft.subjects.map((s,j)=>`<section class="subject" data-subject="${j}"><h3>${s.kind==='island'?'海岛整体':`酒店 ${j}`}</h3>${s.kind==='hotel'?`<label>酒店名称<input data-name="${j}" value="${esc(s.name)}" maxlength="120" required></label><button type="button" data-remove="${j}">移除这个酒店</button>`:''}${dimensions.map((d,i)=>`<div class="rating"><span>${d}</span><span class="stars" data-j="${j}" data-i="${i}" role="slider" tabindex="0" aria-label="${d}" aria-valuemin="0" aria-valuemax="5" aria-valuenow="${s.ratings[i]??0}" aria-valuetext="${s.ratings[i]??'未评分'}">★★★★★<span class="fill" style="width:${(s.ratings[i]??0)*20}%">★★★★★</span></span><output>${s.ratings[i]??'—'}</output><button type="button" data-clear="${j},${i}">留空</button></div>`).join('')}<div class="chart">${radar(s)}</div><label>图下备注<textarea data-note="${j}" rows="3" maxlength="10000">${esc(s.note)}</textarea></label></section>`).join('')}
function open(record){draft=record?structuredClone(record):{id:crypto.randomUUID(),island:'',start:'',end:'',note:'',subjects:[blankSubject()],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};document.body.classList.add('editing');baseRevision=state.revision;for(const k of ['island','start','end','note'])$('#form').elements[k].value=draft[k];$('#source').textContent=draft.sourceRecordedAt?`来源记录时间：${draft.sourceRecordedAt}（不是旅行日期）`:'';$('#saveState').textContent='尚未保存的草稿';subjects();$('#editor').hidden=false;$('#records').hidden=true;$('#new').hidden=true;$('#editor').scrollIntoView({behavior:'instant'})}
function close(){document.body.classList.remove('editing');draft=null;$('#editor').hidden=true;$('#records').hidden=false;$('#new').hidden=false}
function rating(el,v){const j=+el.dataset.j,i=+el.dataset.i;draft.subjects[j].ratings[i]=v;el.querySelector('.fill').style.width=(v??0)*20+'%';el.setAttribute('aria-valuenow',v??0);el.setAttribute('aria-valuetext',v??'未评分');el.nextElementSibling.textContent=v??'—';el.closest('.subject').querySelector('.chart').innerHTML=radar(draft.subjects[j])}
$('#subjects').addEventListener('pointerdown',e=>{const el=e.target.closest('.stars');if(!el)return;el.setPointerCapture(e.pointerId);const apply=e=>{const r=el.getBoundingClientRect();rating(el,Math.max(.5,Math.min(5,Math.ceil((e.clientX-r.left)/r.width*10)/2)))};apply(e);el.onpointermove=e=>{if(el.hasPointerCapture(e.pointerId))apply(e)};el.onpointerup=e=>el.releasePointerCapture(e.pointerId)});
$('#subjects').addEventListener('keydown',e=>{const el=e.target.closest('.stars');if(!el)return;let v=draft.subjects[+el.dataset.j].ratings[+el.dataset.i];if(['ArrowRight','ArrowUp'].includes(e.key))v=Math.min(5,(v??0)+.5);else if(['ArrowLeft','ArrowDown'].includes(e.key))v=v===.5?null:Math.max(.5,(v??1)-.5);else if(e.key==='Home'||e.key==='Delete')v=null;else if(e.key==='End')v=5;else return;e.preventDefault();rating(el,v)});
$('#subjects').addEventListener('input',e=>{if(e.target.dataset.name!==undefined)draft.subjects[+e.target.dataset.name].name=e.target.value;if(e.target.dataset.note!==undefined)draft.subjects[+e.target.dataset.note].note=e.target.value});
$('#subjects').addEventListener('click',e=>{if(e.target.dataset.clear){const [j,i]=e.target.dataset.clear.split(',');rating($(`[data-j="${j}"][data-i="${i}"]`),null)}if(e.target.dataset.remove&&confirm('移除草稿中的这个酒店？')){draft.subjects.splice(+e.target.dataset.remove,1);subjects()}});
$('#new').onclick=()=>open();$('#addHotel').onclick=()=>{draft.subjects.push(blankSubject('hotel'));subjects()};$('#cancel').onclick=()=>{if(confirm('放弃这次编辑？已保存记录不会改变。'))close()};
$('#form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;$('#save').disabled=true;try{for(const k of ['island','start','end','note'])draft[k]=$('#form').elements[k].value.trim();draft.updatedAt=new Date().toISOString();validate(draft);const records=state.records.filter(r=>r.id!==draft.id).concat(structuredClone(draft));state={revision:await write(baseRevision,records),records};close();render();$('#status').textContent='✓ 已确认保存到本机 · '+new Date().toLocaleString()+' · 未云同步'}catch(err){$('#saveState').textContent=err.message}finally{busy=false;$('#save').disabled=false}};
$('#records').onclick=async e=>{if(e.target.dataset.edit)open(state.records.find(r=>r.id===e.target.dataset.edit));if(e.target.dataset.delete&&confirm('确认删除这次旅行？建议先导出备份。')){try{const records=state.records.filter(r=>r.id!==e.target.dataset.delete);state={revision:await write(state.revision,records),records};render()}catch(err){alert(err.message)}}};
$('#export').onclick=()=>{if(!state)return;const url=URL.createObjectURL(new Blob([JSON.stringify({format:'lw5-island-journal',version:1,exportedAt:new Date().toISOString(),records:state.records},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='LW5-海岛备份-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#import').onchange=async e=>{try{if(draft)throw Error('请先保存或取消当前草稿');const file=e.target.files[0];if(!file)return;if(file.size>10000000)throw Error('备份过大');const incoming=parseBackup(await file.text());if(!confirm(`导入 ${incoming.length} 条记录？不会覆盖本地记录；有差异的同一记录将保留冲突副本。`))return;const current=await read(),records=merge(current.records,incoming);state={revision:await write(current.revision,records),records};render();$('#status').textContent='✓ 备份已导入本机 · 未云同步'}catch(err){alert('导入失败：'+err.message)}finally{e.target.value=''}};
$('#persist').onclick=async()=>{$('#retention').textContent=await navigator.storage?.persist?.()?'浏览器已允许持久存储；仍建议保留备份。':'浏览器未授予长期保留，仍可本地保存；请导出备份。'};
window.addEventListener('beforeunload',e=>{if(draft){e.preventDefault();e.returnValue=''}});
try{state=await read();render()}catch(err){$('#status').textContent='无法读取本地存档：'+err.message;$('#new').disabled=true}
if('serviceWorker'in navigator)navigator.serviceWorker.register('../sw.js').catch(()=>{});
