export const dimensions=['景色','交通便利程度','美食','服务','海水','海洋生物','酒店设施','性价比'];
export const blankSubject=(kind='island')=>({id:crypto.randomUUID(),kind,name:'',ratings:Array(8).fill(null),note:''});
const dbp=new Promise((resolve,reject)=>{const r=indexedDB.open('lw5-island-journal',1);r.onupgradeneeded=()=>r.result.createObjectStore('journal');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
export async function read(){const db=await dbp;return new Promise((resolve,reject)=>{const r=db.transaction('journal').objectStore('journal').get('state');r.onsuccess=()=>resolve(r.result||{revision:0,records:[]});r.onerror=()=>reject(r.error)})}
export async function write(expected,records){const db=await dbp;return new Promise((resolve,reject)=>{const tx=db.transaction('journal','readwrite'),s=tx.objectStore('journal'),r=s.get('state');let conflict=false;r.onsuccess=()=>{const state=r.result||{revision:0,records:[]};if(state.revision!==expected){conflict=true;tx.abort();return} s.put({revision:expected+1,records},'state')};tx.oncomplete=()=>resolve(expected+1);tx.onabort=()=>reject(new Error(conflict?'另一窗口已修改存档，请保留草稿并刷新后重试。': '本地保存失败，草稿仍保留。'));tx.onerror=()=>reject(tx.error)})}
const date=v=>v===''||(/^\d{4}-\d{2}-\d{2}$/.test(v)&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v);
export function validate(record){if(!record||typeof record.id!=='string'||typeof record.island!=='string'||!record.island.trim()||record.island.length>120||!date(record.start)||!date(record.end)||record.start&&record.end&&record.start>record.end||typeof record.note!=='string'||record.note.length>10000||!Array.isArray(record.subjects)||!record.subjects.length||record.subjects.length>50)throw Error('记录格式或旅行日期无效');for(const s of record.subjects){if(!['island','hotel'].includes(s.kind)||typeof s.name!=='string'||s.name.length>120||s.kind==='hotel'&&!s.name.trim()||typeof s.note!=='string'||s.note.length>10000||!Array.isArray(s.ratings)||s.ratings.length!==8||s.ratings.some(v=>v!==null&&(typeof v!=='number'||v<.5||v>5||v*2%1)))throw Error('酒店名称或评分无效')}for(const k of ['createdAt','updatedAt'])if(typeof record[k]!=='string'||!Number.isFinite(Date.parse(record[k])))throw Error('记录时间无效');return record}
export function parseBackup(text){const b=JSON.parse(text);if(b.format!=='lw5-island-journal'||b.version!==1||!Array.isArray(b.records)||b.records.length>2000)throw Error('不支持的备份格式');const ids=new Set();for(const r of b.records){validate(r);if(ids.has(r.id))throw Error('备份包含重复记录');ids.add(r.id)}return b.records}
export function merge(local,incoming){const result=structuredClone(local);for(const record of incoming){const old=result.find(r=>r.id===record.id);if(!old)result.push({...record,importedAt:new Date().toISOString()});else if(JSON.stringify(old)!==JSON.stringify(record)){const comparable=r=>JSON.stringify({...r,id:undefined,conflictOf:undefined,importedAt:undefined});if(comparable(old)!==comparable(record)&&!result.some(r=>r.conflictOf===record.id&&comparable(r)===comparable(record)))result.push({...record,id:crypto.randomUUID(),conflictOf:record.id,importedAt:new Date().toISOString()})}}return result}
